import olympiad;
import cse5;
unitsize(3inch);
pair A, B, C;
pair offset = (0, 0);
real k = 1; 
A = (0, 0) * k + offset;
B = (1, 0) * k + offset; 
C = (1/2, sqrt(3)/2) * k + offset;
pair G = (A + B + C)/3;
pair O = (0, k/sqrt(3)) + offset;
real radius = k/sqrt(3);
draw(A -- B -- C -- cycle);
dot(A); dot(B); dot(C); dot(O); dot(G);
draw(circle(O, radius));
    real i = 47.4;
    pair P = O + radius * dir(-i);
    pair N = intersectionpoints(A -- (100*(P - A) + P),  B -- C)[0];
    pair M = intersectionpoints(C -- (100*(P - C) + P),  B -- A)[0];
    path AN = A -- N;
    path CM = C -- M;
    draw(AN); draw(CM); 
    dot(P); dot(N); dot(M);
    draw(circumcircle(B, N, M));
    pair L_P = circumcenter(B, N, M);
    dot(L_P); 
